name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/richmorj/ambel:19may22
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test
      run: |
        sbt -v +"testOnly ambel.Apb2NetUnitTester -- -Dbackend=verilator"
        # sbt -v +"testOnly ambel.Apb2SliceUnitTester -- -Dbackend=verilator"
        # sbt -v +"testOnly ambel.Apb2CSTrgtUnitTester -- -Dbackend=verilator"
        # sbt -v +"testOnly ambel.Apb2RegFileUnitTester -- -Dbackend=verilator"
        echo "Generating coverage reports..."
        ./mergeModuleCov.bash Apb2Net
        # mergeModuleCov.bash Apb2Slice
        # mergeModuleCov.bash Apb2CSTrgt
        # mergeModuleCov.bash Apb2RegFile
        ./genCovReport.bash
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v3
      with:
        path: coverage/html

