name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/richmorj/ambel:20may22
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test
      run: |
        sbt -v +"testOnly ambel.Apb2NetUnitTester -- -Dbackend=verilator"
        # sbt -v +"testOnly ambel.Apb2SliceUnitTester -- -Dbackend=verilator"
        # sbt -v +"testOnly ambel.Apb2CSTrgtUnitTester -- -Dbackend=verilator"
        # sbt -v +"testOnly ambel.Apb2RegFileUnitTester -- -Dbackend=verilator"
        echo "Generating coverage reports..."
        ./src/main/scripts/mergeModuleCov.bash Apb2Net
        ./src/main/scripts/mergeModuleCov.bash Apb2Slice
        ./src/main/scripts/mergeModuleCov.bash Apb2CSTrgt
        ./src/main/scripts/mergeModuleCov.bash Apb2RegFile
        ./src/main/scripts/genCovReport.bash
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v3
      with:
        path: coverage/html
    - name: Create Badges Directory
      run: mkdir -p .github/badges
    - name: Generate Coverage Badge
      run: |
        node ./src/main/scripts/covbadge.js > .github/badges/covbadge.svg
    - name: Commit Badge
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add .github/badges/covbadge.svg
        git commit -m "Add/update coverage badge"
    - name: Push Coverage Badge commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
