name: CI
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/richmorj/ambel:20may22
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Work-around Permission Issue
      run: git config --global --add safe.directory /__w/ambel/ambel
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test
      run: |
        sbt -v +"testOnly ambel.Apb2NetUnitTester -- -Dbackend=verilator"
        sbt -v +"testOnly ambel.Apb2SliceUnitTester -- -Dbackend=verilator"
        sbt -v +"testOnly ambel.Apb2CSTrgtUnitTester -- -Dbackend=verilator"
        sbt -v +"testOnly ambel.Apb2RegFileUnitTester -- -Dbackend=verilator"
        sbt -v +"testOnly ambel.SimpleApb2CSTrgtUnitTester -- -Dbackend=verilator"
        echo "Generating coverage reports..."
        ./src/main/scripts/mergeModuleCov.bash
        ./src/main/scripts/genCovReport.bash
    # - name: Upload Coverage to codecov.io
      # run: |
      #   curl -Os https://uploader.codecov.io/latest/linux/codecov
      #   chmod +x codecov
      # Can't figure out how to get codecov working with lcov txt reports
      # uses: codecov/codecov-action@v2
      # with:
      #   directory: ./coverage/
      #   fail_ci_if_error: true
      #   path_to_write_report: ./coverage/codecov_report.txt
      #   verbose: true
    - name: Install rsync for github-pages-deploy-action
      run: |
        apt-get update && apt-get install -y rsync
    - name: Publish HTML Coverage to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: coverage/html
        target-folder: coverage
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v3
      with:
        path: coverage/html
    - name: Create Badges Directory
      run: mkdir -p badges
    - name: Generate Coverage Badge
      run: |
        node ./src/main/scripts/covbadge.js > badges/coverage.svg
    - name: Publish Coverage Badge to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: badges
        target-folder: badges

